name: graphql_codegen
description: |
  Simple, opinionated, codegen library for GraphQL. It allows you to
  generate serializers and client helpers to easily call and parse your data.

version: 5.1.4
homepage: https://github.com/heftapp/graphql_codegen/tree/main/packages/graphql_codegen
repository: https://github.com/heftapp/graphql_codegen/tree/main/packages/graphql_codegen

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  gql: ^0.14.0
  build: ^2.3.1
  glob: ^2.1.1
  code_builder: ^4.4.0
  dart_style: ^2.2.4
  built_collection: ^5.1.1
  path: ^1.8.2
  gql_code_builder: ^0.7.0
  recase: ^4.1.0
  json_annotation: ^4.8.0
dev_dependencies:
  test: ^1.22.2
  build_test: ^2.1.6
  build_runner: ^2.3.3
  json_serializable: ^6.6.0
  graphql: ^5.1.1
  lints: ^2.0.1
